apiVersion: batch/v1
kind: CronJob
metadata:
  name: trace-auditor
  namespace: default
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/hostname: vector
          containers:
          - name: auditor
            image: trace-auditor:0.1.0 # Using local imported image
            imagePullPolicy: Never
            envFrom:
            - secretRef:
                name: trace-auditor-secrets
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi
